<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'BaseBook' => 'om/BaseBook.php',
  'BaseBookPeer' => 'om/BaseBookPeer.php',
  'BaseBookQuery' => 'om/BaseBookQuery.php',
  'Book' => 'Book.php',
  'BookPeer' => 'BookPeer.php',
  'BookQuery' => 'BookQuery.php',
  'BookTableMap' => 'map/BookTableMap.php',
);