<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'BaseTicket' => 'om/BaseTicket.php',
  'BaseTicketPeer' => 'om/BaseTicketPeer.php',
  'BaseTicketQuery' => 'om/BaseTicketQuery.php',
  'Ticket' => 'Ticket.php',
  'TicketPeer' => 'TicketPeer.php',
  'TicketQuery' => 'TicketQuery.php',
  'TicketTableMap' => 'map/TicketTableMap.php',
);