<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /home/ubuntu/www/hcr-web/config/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'icrobot' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=icrobot',
        'user' => 'web',
        'password' => 'GjZS3pvLYbSeydGb',
      ),
    ),
    'default' => 'icrobot',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-hcr-conf.php');
return $conf;