<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file F:\Documents\GitHub\hcr-web\config\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'hcr' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=hcr',
        'user' => 'web',
        'password' => 'robot',
      ),
    ),
    'default' => 'hcr',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-hcr-conf.php');
return $conf;